version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    environment:
      - STOCKS_SERVICE_URL=http://stocks:8080
      - ORDER_SERVICE_URL=http://order:8090
    ports:
      - "8000:8000"
  
  stocks:
    build:
      context: ./stocks
    volumes:
      - stocks-db:/var/lib/stocks-db
    environment:
      - STOCKS_DB_PATH=/var/lib/stocks-db/stock.db

  order:
    build:
      context: ./order
    volumes:
      - order-db:/var/lib/order-db
    environment:
      - ORDER_DB_PATH=/var/lib/order-db/order.db
      - STOCKS_SERVICE_URL=http://stocks:8080
    ports:
      - "8090:8090"

volumes:
  stocks-db:
  order-db: