apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: order-db
  name: order-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
