apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: dex-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - name: dex
        image: dexidp/dex:v2.39.0
        command: ["/usr/local/bin/dex"]
        args: ["serve", "/etc/dex/dex-config.yaml"]
        ports:
        - containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dex-config
