apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: alpha-stocks-dev
spec:
  type: NodePort
  ports:
  - port: 5556
    targetPort: 5556
    nodePort: 32000
    protocol: TCP
    name: http
  selector:
    app: dex
